---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: appOfApps
    repoURL: https://github.com/WesleyCharlesBlake/ghost-blog-demo.git
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
